version: '3.4'
services:
  fluentsearch-fe:
    container_name: FluentSearch-FE
    restart: always
    environment:
      NODE_ENV: 'development'
      TZ: Asia/Bangkok
      APP_BACKEND_ENDPOINT:  'http://localhost:5000/'
      APP_GRAPHQL_ENDPOINT: 'http://localhost:5000/graphql'
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - './src:/src'
    logging:
      options:
        max-size: 50m
        