name: Automate Build and Testing

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14-latest
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn build
  storybook:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14-latest
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn
      - run: yarn build-storybook
