name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run lint
      - run: yarn test:ci
      - run: yarn run build
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fluentsearch-fe:$(date +%s)
