name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '14.3'
          registry-url: https://registry.npmjs.org
          scope: '@octocat'
      - name: run CI
        run: |
          yarn install
          yarn run lint
          yarn run test
          yarn run build
